version: '3'

services:
  accounting-mysql:
    image: mysql:8.0
    volumes:
      - accounting-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ACCOUNTING
      - MYSQL_USER=ACCOUNTING_USER
      - MYSQL_PASSWORD=ACCOUNTING_PASS
    ports:
      - 3307:3306
    networks:
      - accounting-net

  accounting-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - accounting-redis-volume:/data

  accounting-api:
    image: accounting-api-image:latest
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:mysql://accounting-mysql:3306/ACCOUNTING?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_DATASOURCE_URL=jdbc:mysql://accounting-mysql:3306/mysql
    depends_on:
      - accounting-mysql
      - accounting-redis
    networks:
      - accounting-net

volumes:
  accounting-mysql-volume:
  accounting-redis-volume:
networks:
  accounting-net:
    driver: bridge